// Contenu éditorial propre à chaque arrondissement.
//
// Les pages /notaire-paris/8eme et /notaire-paris/19eme servaient exactement le
// même texte, seul le numéro changeait : pour un moteur de recherche, vingt
// pages quasi identiques valent une seule page reléguée. Or ces quartiers n'ont
// rien de comparable — 707 études référencées dans le 8ème contre 6 dans le
// 19ème, un quartier d'affaires face à un tissu résidentiel.
//
// On s'en tient à ce qui est stable et vérifiable : quartiers, caractère
// dominant, types d'actes qui en découlent. Aucun prix au m² : ces chiffres
// bougent chaque trimestre et une page qui vieillit mal dessert le référencement.

export interface ContenuArrondissement {
  quartiers: string[];
  /** Deux phrases insérées dans le chapô, sous le titre. */
  profil: string;
  /** Question propre à l'arrondissement, ajoutée en tête de la FAQ. */
  question: { q: string; a: string };
}

const P = (quartiers: string[], profil: string, q: string, a: string): ContenuArrondissement =>
  ({ quartiers, profil, question: { q, a } });

export const PARIS: Record<number, ContenuArrondissement> = {
  1: P(["Louvre", "Châtelet", "Palais-Royal", "Les Halles", "Place Vendôme"],
    "Le 1er arrondissement compte peu d'habitants pour beaucoup d'activité économique : sièges sociaux, commerces et hôtels particuliers y dominent. Les études du quartier traitent donc surtout des cessions de fonds de commerce, des baux commerciaux et de l'immobilier de prestige.",
    "Quels actes traite-t-on le plus souvent dans le 1er arrondissement ?",
    "Le tissu du 1er étant très largement commercial et tertiaire, les notaires du secteur sont fréquemment sollicités pour des cessions de fonds de commerce, des baux commerciaux, des constitutions de sociétés et des ventes d'appartements haussmanniens ou d'hôtels particuliers."),
  2: P(["Bourse", "Sentier", "Grands Boulevards", "Montorgueil", "Mail"],
    "Cœur historique des affaires parisiennes, le 2ème mêle sièges d'entreprises, commerces du Sentier et immeubles anciens réhabilités. Les questions de droit des sociétés y côtoient les ventes de petites surfaces.",
    "Un notaire du 2ème peut-il m'accompagner pour ma société ?",
    "Oui. Le 2ème arrondissement concentre une forte densité d'entreprises et les notaires du secteur pratiquent couramment la constitution de sociétés, la cession de parts et de fonds de commerce, en complément de leur activité immobilière."),
  3: P(["Marais nord", "Arts-et-Métiers", "Temple", "Enfants-Rouges"],
    "Le 3ème est un arrondissement d'immeubles anciens et de copropriétés de petite taille, où les biens se transmettent souvent au sein des familles. Indivisions et successions y occupent une place importante.",
    "Pourquoi les indivisions sont-elles fréquentes dans le 3ème ?",
    "Le bâti ancien du Marais se transmet largement par héritage, ce qui crée des indivisions entre héritiers. Les notaires du 3ème sont habitués à ces situations : partage, licitation, rachat de soulte entre indivisaires."),
  4: P(["Marais sud", "Île Saint-Louis", "Hôtel de Ville", "Saint-Paul", "Saint-Gervais"],
    "Entre l'Île Saint-Louis et le Marais, le 4ème réunit un patrimoine ancien exceptionnel et des biens de forte valeur. Les successions y portent souvent sur des immeubles détenus de longue date.",
    "Le patrimoine classé change-t-il quelque chose à une vente dans le 4ème ?",
    "Oui, une partie du 4ème est en secteur sauvegardé : servitudes d'urbanisme, contraintes de travaux et droit de préemption doivent être vérifiés avant la vente. Un notaire du secteur connaît ces règles et sécurise l'acte en conséquence."),
  5: P(["Quartier latin", "Panthéon", "Jussieu", "Mouffetard", "Val-de-Grâce"],
    "Arrondissement universitaire par excellence, le 5ème voit beaucoup d'investissement locatif sur de petites surfaces, aux côtés d'un patrimoine familial ancien.",
    "Le 5ème est-il adapté à un investissement locatif étudiant ?",
    "C'est l'un des secteurs les plus demandés de Paris pour la location étudiante, avec la Sorbonne, Jussieu et de nombreuses grandes écoles. Un notaire du 5ème pourra vous conseiller sur le régime fiscal du meublé et la rédaction du bail."),
  6: P(["Saint-Germain-des-Prés", "Odéon", "Luxembourg", "Notre-Dame-des-Champs"],
    "Le 6ème est l'un des arrondissements les plus recherchés de Paris. Les opérations y engagent des montants élevés et la préparation patrimoniale — donation, démembrement — y est courante.",
    "Faut-il anticiper la transmission d'un bien dans le 6ème ?",
    "Compte tenu des valeurs en jeu, oui : donation-partage, démembrement de propriété ou apport à une SCI familiale permettent d'organiser la transmission. Un notaire du 6ème vous chiffrera précisément l'impact fiscal de chaque option."),
  7: P(["Invalides", "Champ-de-Mars", "Gros-Caillou", "Saint-Thomas-d'Aquin", "École Militaire"],
    "Le 7ème concentre hôtels particuliers et grands appartements familiaux, souvent détenus depuis plusieurs générations. Les dossiers de succession y sont fréquents et rarement simples.",
    "Combien de temps prend une succession dans le 7ème ?",
    "Une succession portant sur un bien parisien de valeur demande généralement six à douze mois : évaluation, accord des héritiers, déclaration fiscale. Le délai s'allonge en cas d'indivision ou de démembrement, situations courantes dans le 7ème."),
  8: P(["Champs-Élysées", "Madeleine", "Monceau", "Europe", "Saint-Lazare"],
    "Le 8ème est le premier quartier d'affaires de Paris intra-muros et rassemble le plus grand nombre d'études de la capitale. Droit des sociétés, immobilier d'entreprise et opérations patrimoniales s'y croisent en permanence.",
    "Pourquoi y a-t-il autant de notaires dans le 8ème ?",
    "L'arrondissement accueille une densité exceptionnelle de sièges sociaux, de sociétés et d'immobilier tertiaire. Cette concentration d'activité économique explique que le 8ème compte de loin le plus grand nombre d'études notariales de Paris."),
  9: P(["Opéra", "Saint-Georges", "Trinité", "Pigalle", "Faubourg-Montmartre"],
    "Le 9ème associe immeubles haussmanniens, sièges d'entreprises et vie commerçante. Les copropriétés anciennes y génèrent beaucoup de ventes et de questions de charges.",
    "Que vérifier avant d'acheter en copropriété dans le 9ème ?",
    "Le bâti haussmannien implique d'examiner les procès-verbaux d'assemblée, les travaux votés et le fonds de travaux avant de s'engager. Le notaire rassemble ces pièces et vous alerte sur les charges à venir."),
  10: P(["Canal Saint-Martin", "Gare du Nord", "Gare de l'Est", "République", "Château-d'Eau"],
    "Porte d'entrée du nord de Paris, le 10ème attire beaucoup de primo-accédants et connaît une forte activité de baux commerciaux le long des grands axes.",
    "Le 10ème convient-il à un premier achat ?",
    "C'est l'un des arrondissements centraux les plus accessibles pour un premier achat. Le notaire vous accompagne sur le prêt, le calcul des frais d'acquisition et les dispositifs d'aide au primo-accédant."),
  11: P(["Bastille", "Oberkampf", "Charonne", "Roquette", "Sainte-Marguerite"],
    "Très habité et prisé des jeunes actifs, le 11ème enregistre un volume important de transactions sur des surfaces moyennes, souvent en copropriété.",
    "Combien de temps faut-il pour acheter dans le 11ème ?",
    "Entre la signature du compromis et l'acte authentique, comptez deux à trois mois, le temps de purger le droit de préemption, d'obtenir le prêt et de réunir les pièces d'urbanisme."),
  12: P(["Bercy", "Nation", "Daumesnil", "Bois de Vincennes", "Picpus"],
    "Arrondissement familial et verdoyant, le 12ème voit beaucoup d'acquisitions de résidences principales et de transmissions entre générations.",
    "Comment protéger mon conjoint lors d'un achat dans le 12ème ?",
    "Selon votre situation, le notaire peut proposer une acquisition en tontine, une donation entre époux ou un aménagement du régime matrimonial. Le choix se fait au regard de votre situation familiale et patrimoniale."),
  13: P(["Place d'Italie", "Butte-aux-Cailles", "Bibliothèque", "Olympiades", "Gobelins"],
    "Le 13ème mêle grands ensembles des années 1970 et programmes neufs du secteur Paris Rive Gauche. Les ventes en l'état futur d'achèvement y sont fréquentes.",
    "Qu'est-ce qui change quand on achète dans le neuf dans le 13ème ?",
    "Un achat en VEFA suit un calendrier propre : contrat de réservation, appels de fonds échelonnés, garanties du constructeur, livraison. Le notaire vérifie le contrat et sécurise chaque étape du paiement."),
  14: P(["Montparnasse", "Alésia", "Denfert-Rochereau", "Plaisance", "Petit-Montrouge"],
    "Le 14ème est un arrondissement résidentiel apprécié des familles, avec un parc immobilier ancien qui donne lieu à de nombreuses successions.",
    "Faut-il faire évaluer un bien du 14ème avant une succession ?",
    "Oui, l'évaluation conditionne les droits de succession et l'équilibre du partage entre héritiers. Le notaire s'appuie sur les ventes comparables du quartier pour retenir une valeur défendable devant l'administration."),
  15: P(["Vaugirard", "Convention", "Grenelle", "Beaugrenelle", "Javel"],
    "Arrondissement le plus peuplé de Paris, le 15ème concentre logiquement un volume élevé de ventes et d'acquisitions de résidences principales.",
    "Le 15ème est-il un arrondissement recherché des familles ?",
    "C'est le plus peuplé de la capitale, avec une offre importante de logements familiaux et d'équipements. Le volume de transactions y est parmi les plus élevés de Paris, tous types de biens confondus."),
  16: P(["Passy", "Auteuil", "Trocadéro", "Muette", "Chaillot"],
    "Le 16ème est un arrondissement de patrimoine familial, où les biens restent souvent plusieurs générations dans la même famille. Donations-partages et démembrements y sont courants.",
    "Qu'est-ce qu'une donation-partage et pourquoi est-elle fréquente dans le 16ème ?",
    "Elle permet de répartir de son vivant ses biens entre ses enfants, en figeant leur valeur au jour de l'acte et en évitant les conflits ultérieurs. C'est un outil très utilisé là où le patrimoine familial est important."),
  17: P(["Batignolles", "Ternes", "Monceau", "Clichy", "Épinettes"],
    "Le 17ème juxtapose quartiers d'affaires et zones résidentielles, avec le secteur Clichy-Batignolles qui a apporté un volume important de logements neufs.",
    "Achat neuf ou ancien dans le 17ème : quelles différences ?",
    "Les frais d'acquisition sont nettement plus faibles dans le neuf, mais le calendrier de livraison et les garanties diffèrent. Le notaire compare les deux options chiffres en main avant que vous vous engagiez."),
  18: P(["Montmartre", "Abbesses", "La Chapelle", "Goutte d'Or", "Clignancourt"],
    "Le 18ème présente de forts contrastes, entre les pentes de Montmartre et les quartiers populaires du nord. Primo-accession et copropriétés anciennes y dominent.",
    "Quelles vérifications avant d'acheter dans le 18ème ?",
    "L'état de la copropriété mérite un examen attentif : travaux votés, impayés de charges, éventuelle procédure en cours. Le notaire réunit ces éléments et vous signale les points de vigilance avant la signature."),
  19: P(["Buttes-Chaumont", "La Villette", "Ourcq", "Belleville", "Danube"],
    "Arrondissement résidentiel du nord-est parisien, le 19ème compte peu d'études sur son territoire. Ses habitants s'adressent souvent à un notaire d'un arrondissement voisin, ou consultent à distance.",
    "Que faire s'il y a peu de notaires dans le 19ème ?",
    "Vous n'êtes pas tenu de choisir un notaire de votre arrondissement : le choix est entièrement libre en France, et le rendez-vous peut se tenir en visioconférence. Les études des arrondissements voisins interviennent couramment sur le 19ème."),
  20: P(["Ménilmontant", "Gambetta", "Père-Lachaise", "Saint-Fargeau", "Charonne"],
    "Le 20ème est un arrondissement résidentiel en évolution, où les primo-accédants sont nombreux. Peu d'études y sont implantées.",
    "Puis-je consulter un notaire hors du 20ème pour un bien situé dans le 20ème ?",
    "Oui, sans aucune restriction. Le notaire est compétent sur l'ensemble du territoire national : le lieu de son étude n'a aucune incidence sur la validité de l'acte ni sur ses tarifs, qui sont réglementés."),
};

export const LYON: Record<number, ContenuArrondissement> = {
  1: P(["Terreaux", "Pentes de la Croix-Rousse", "Opéra", "Martinière"],
    "Le 1er arrondissement de Lyon est celui des pentes et du bâti ancien, avec beaucoup de petites copropriétés et d'investissement locatif.",
    "Qu'implique l'achat d'un bien ancien dans les pentes ?",
    "Le bâti des pentes est souvent ancien et en copropriété réduite : diagnostics, état de l'immeuble et travaux votés doivent être examinés de près. Le notaire réunit ces pièces avant la signature."),
  2: P(["Bellecour", "Presqu'île", "Confluence", "Perrache", "Ainay"],
    "La Presqu'île concentre commerces et sièges d'entreprises, tandis que Confluence a apporté un important parc de logements neufs.",
    "Confluence : que vérifier avant d'acheter dans le neuf ?",
    "Les programmes de Confluence relèvent le plus souvent de la VEFA : échéancier des appels de fonds, garantie financière d'achèvement et date de livraison sont les points que le notaire contrôle pour vous."),
  3: P(["Part-Dieu", "Guillotière", "Montchat", "Villette", "Préfecture"],
    "Premier quartier d'affaires de Lyon, le 3ème arrondissement conjugue immobilier tertiaire et quartiers résidentiels comme Montchat.",
    "Un notaire du 3ème peut-il traiter un dossier d'entreprise ?",
    "Oui. La proximité de la Part-Dieu fait que les études du 3ème pratiquent couramment le droit des sociétés : constitution, cession de parts, baux commerciaux et immobilier d'entreprise."),
  4: P(["Plateau de la Croix-Rousse", "Boulevard des Canuts", "Serin"],
    "Le plateau de la Croix-Rousse est un quartier résidentiel familial au bâti caractéristique, hérité des ateliers de canuts.",
    "Les appartements de canuts posent-ils des questions particulières ?",
    "Leurs grandes hauteurs sous plafond donnent souvent lieu à des mezzanines, dont la conformité et la surface habitable doivent être vérifiées. Le notaire s'assure que la surface annoncée correspond à la réalité."),
  5: P(["Vieux-Lyon", "Fourvière", "Saint-Just", "Point du Jour", "Saint-Georges"],
    "Le 5ème abrite le Vieux-Lyon, inscrit au patrimoine mondial de l'UNESCO, ce qui encadre strictement les travaux et les transformations.",
    "Le classement UNESCO limite-t-il les travaux dans le Vieux-Lyon ?",
    "Oui, le secteur sauvegardé impose des règles précises sur les façades, les menuiseries et les toitures. Ces contraintes doivent être connues avant l'achat : le notaire vérifie les servitudes attachées au bien."),
  6: P(["Parc de la Tête d'Or", "Foch", "Brotteaux", "Masséna"],
    "Le 6ème est l'arrondissement résidentiel le plus recherché de Lyon, avec un patrimoine familial souvent transmis par donation ou succession.",
    "Comment organiser la transmission d'un bien dans le 6ème ?",
    "Donation-partage, démembrement ou SCI familiale : plusieurs outils permettent d'anticiper. Le notaire compare leur coût fiscal au regard de votre situation familiale."),
  7: P(["Jean Macé", "Gerland", "Guillotière", "Saxe-Gambetta"],
    "Le 7ème accueille de nombreux étudiants et voit se développer le secteur de Gerland, avec un fort volume d'investissement locatif.",
    "Investir dans le locatif à Gerland : quelles précautions ?",
    "Vérifiez le régime fiscal retenu, la nature du bail et l'état du programme si le bien est neuf. Le notaire vous alerte sur les engagements de durée liés aux dispositifs d'investissement."),
  8: P(["Monplaisir", "États-Unis", "Bachut", "Grand Trou"],
    "Arrondissement résidentiel et populaire, le 8ème attire beaucoup de primo-accédants sur des surfaces familiales.",
    "Quelles aides pour un premier achat dans le 8ème ?",
    "Prêt à taux zéro et dispositifs locaux peuvent s'appliquer selon vos revenus et le type de bien. Le notaire vérifie votre éligibilité et intègre ces prêts au plan de financement."),
  9: P(["Vaise", "Gorge de Loup", "La Duchère", "Saint-Rambert"],
    "Le 9ème connaît un important renouvellement urbain, notamment à La Duchère, avec une offre significative de logements neufs.",
    "Acheter dans un quartier en rénovation : quels points de vigilance ?",
    "Renseignez-vous sur le calendrier des opérations en cours et sur les servitudes d'urbanisme du secteur. Le notaire consulte ces documents et vous indique ce qui est engagé autour du bien."),
};

export const MARSEILLE: Record<number, ContenuArrondissement> = {
  1: P(["Belsunce", "Noailles", "Canebière", "Opéra", "Thiers"],
    "Le 1er arrondissement est le centre commerçant historique de Marseille : baux commerciaux et cessions de fonds y sont fréquents.",
    "Comment se passe une cession de fonds de commerce dans le centre ?",
    "Elle suppose de vérifier le bail, les autorisations d'exploitation et les dettes attachées au fonds. Le notaire séquestre le prix le temps des formalités, ce qui protège l'acheteur comme le vendeur."),
  2: P(["Joliette", "Le Panier", "Euroméditerranée", "Arenc", "Vieux-Port"],
    "Le 2ème est au cœur du projet Euroméditerranée, avec de nombreux programmes neufs de bureaux et de logements.",
    "Qu'est-ce qui change dans le périmètre d'Euroméditerranée ?",
    "Ce périmètre d'aménagement comporte des règles d'urbanisme propres et des opérations encore en cours. Le notaire vérifie les servitudes et l'avancement du programme avant la signature."),
  3: P(["Belle-de-Mai", "Saint-Mauront", "La Villette", "National"],
    "Le 3ème fait l'objet d'une importante politique de renouvellement urbain, avec une part significative de primo-accédants.",
    "L'état du bâti ancien est-il un enjeu dans le 3ème ?",
    "Oui. Certains immeubles anciens font l'objet d'arrêtés de péril ou de procédures de ravalement. Le notaire interroge la commune et vous informe de toute procédure en cours sur l'immeuble."),
  4: P(["Les Chartreux", "Cinq-Avenues", "Longchamp", "Blancarde"],
    "Arrondissement résidentiel de centre-ville, le 4ème est marqué par des copropriétés anciennes et une population familiale installée.",
    "Que regarder dans une copropriété ancienne du 4ème ?",
    "Charges, travaux votés et éventuels impayés déterminent le coût réel de votre acquisition. Ces éléments figurent dans les documents que le notaire réunit avant l'acte."),
  5: P(["Baille", "Le Camas", "La Conception", "Chave"],
    "Proche des facultés et des hôpitaux, le 5ème est un secteur actif pour l'investissement locatif.",
    "Le 5ème est-il adapté à la location étudiante ?",
    "La proximité de la Timone et des facultés en fait un secteur recherché. Le notaire vous conseille sur le choix entre location nue et meublée, dont les régimes fiscaux diffèrent sensiblement."),
  6: P(["Castellane", "Préfecture", "Notre-Dame-du-Mont", "Vauban", "Baille"],
    "Le 6ème est l'un des secteurs résidentiels les plus demandés du centre de Marseille, avec un parc majoritairement en copropriété.",
    "Combien de temps prend un achat dans le 6ème ?",
    "Comptez deux à trois mois entre le compromis et l'acte authentique, le temps de réunir les diagnostics, d'obtenir le prêt et de purger les droits de préemption."),
  7: P(["Endoume", "Saint-Victor", "Vallon des Auffes", "Corniche", "Malmousque"],
    "Bord de mer et vues dégagées font du 7ème un secteur de biens à forte valeur, où les transmissions familiales sont fréquentes.",
    "Un bien en bord de mer demande-t-il des vérifications spécifiques ?",
    "Servitudes de vue, proximité du domaine public maritime et règles d'urbanisme littorales doivent être contrôlées. Le notaire consulte ces documents avant de sécuriser la vente."),
  8: P(["Le Prado", "Périer", "Bonneveine", "Pointe Rouge", "Roucas Blanc"],
    "Le 8ème est l'arrondissement résidentiel haut de gamme de Marseille : successions et donations y portent souvent sur des patrimoines importants.",
    "Faut-il anticiper une succession dans le 8ème ?",
    "Lorsque le patrimoine est significatif, l'anticipation réduit sensiblement les droits à payer : donation-partage, démembrement ou assurance-vie. Le notaire chiffre chaque option."),
  9: P(["Mazargues", "Sainte-Marguerite", "Luminy", "Les Calanques", "Sormiou"],
    "Aux portes du parc national des Calanques, le 9ème est un secteur pavillonnaire où les maisons individuelles dominent.",
    "La proximité du parc des Calanques a-t-elle un impact sur une vente ?",
    "Les terrains proches du parc national sont soumis à des règles d'urbanisme strictes, qui limitent les possibilités de construire ou d'agrandir. Le notaire vérifie ces contraintes avant l'acte."),
  10: P(["Saint-Loup", "La Capelette", "Pont-de-Vivaux", "Menpenti"],
    "Arrondissement résidentiel de l'est marseillais, le 10ème accueille de nombreux primo-accédants.",
    "Quelles aides pour un premier achat dans le 10ème ?",
    "Le prêt à taux zéro et certains dispositifs locaux peuvent s'appliquer. Le notaire vérifie votre éligibilité et intègre ces prêts dans le financement de l'acquisition."),
  11: P(["La Valentine", "Saint-Menet", "Les Camoins", "La Treille"],
    "Le 11ème est un arrondissement périurbain, où les maisons individuelles et les terrains constructibles sont fréquents.",
    "Que vérifier avant d'acheter un terrain dans le 11ème ?",
    "Constructibilité, viabilisation et servitudes de passage sont les trois points à contrôler. Le notaire demande le certificat d'urbanisme, qui fixe précisément ce qui est autorisé."),
  12: P(["Saint-Barnabé", "Les Caillols", "Montolivet", "Saint-Julien"],
    "Le 12ème est un secteur pavillonnaire familial, où les biens se transmettent souvent entre générations.",
    "Comment se règle une succession portant sur une maison familiale ?",
    "Il faut évaluer le bien, recueillir l'accord des héritiers et décider entre vente et partage. Le notaire établit l'acte de notoriété puis la déclaration de succession."),
  13: P(["Château-Gombert", "Saint-Jérôme", "Malpassé", "Technopôle"],
    "Le 13ème accueille le technopôle de Château-Gombert et une part importante de logements récents.",
    "Acheter dans le neuf dans le 13ème : quelles garanties ?",
    "Garantie financière d'achèvement, garantie de parfait achèvement et garantie décennale protègent l'acquéreur. Le notaire vérifie leur existence avant le premier appel de fonds."),
  14: P(["Saint-Barthélemy", "Le Canet", "Sainte-Marthe", "Les Arnavaux"],
    "Arrondissement des quartiers nord, le 14ème fait l'objet de programmes de renouvellement urbain.",
    "Acheter dans un secteur en renouvellement urbain, quelles précautions ?",
    "Renseignez-vous sur les opérations programmées autour du bien et sur d'éventuelles procédures visant l'immeuble. Le notaire interroge la commune sur ces points."),
  15: P(["Saint-Antoine", "La Cabucelle", "Verduron", "Les Aygalades"],
    "Le 15ème est un arrondissement populaire du nord de Marseille, avec une forte proportion de primo-accédants.",
    "Un premier achat dans le 15ème est-il accessible ?",
    "C'est l'un des secteurs les plus abordables de Marseille. Le notaire vous détaille le coût total de l'opération, frais d'acquisition compris, avant que vous vous engagiez."),
  16: P(["L'Estaque", "Saint-André", "Les Riaux", "Saint-Henri"],
    "Ancien village portuaire, le 16ème conserve un habitat de maisons de ville souvent transmises au sein des familles.",
    "Les maisons de village posent-elles des difficultés particulières ?",
    "Mitoyenneté, servitudes de passage et limites de propriété méritent d'être vérifiées, les titres anciens étant parfois imprécis. Le notaire fait le point avant la vente."),
};

export const CONTENUS: Record<string, Record<number, ContenuArrondissement>> = {
  Paris: PARIS,
  Lyon: LYON,
  Marseille: MARSEILLE,
};
